version: '3.8'
services:
  auth_db:
    image: postgres:16.3-alpine
    container_name: auth_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
    ports:
      - "5431:5432"
    volumes:
      - "auth_db:/var/lib/postgresql/data"
    networks:
      - auth_service
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 3


volumes:
  auth_db:
    name: auth_db


networks:
  auth_service:
    external: false